name: Publish
on:
    workflow_dispatch:
#   release:
#     types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      uses: coursier/setup-action@v1
      with:
        jvm: "adopt:11"
    - name: "Publish package"
      run: sbt publish # add test
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
